### ISSUE TITLE
git branch problem

### ISSUE THREAD

**Issue by karthikvijay** [AbdealiJK/dashboard#19]
Im trying to push my code to github for others to see and comment.
I tried creating a branch and there was some error when I tried to push. The error is :
```
han@han-Lenovo-B460e:~/dashboard$ git push origin application
Username for 'https://github.com': karthikvijay
Password for 'https://karthikvijay@github.com': 
error: src refspec application does not match any.
error: failed to push some refs to 'https://github.com/AbdealiJK/dashboard.git'
```

The steps i did were :
1. Created a branch in github using the GUI in the main repository page
2. Then I tried to push using the command :
```git push origin application```

**Comment by AbdealiJK** [comment]
@karthikvijay ... I can see that your branch exists here : https://github.com/AbdealiJK/dashboard/tree/application
it br
This is on git ... did you pull after you made the branch using github Branches ?
You most probably do not have the branch in your local repo...

You can check branched you have in your local computer by doing : `git branch -a` The ones with "origin" exist on github. Can you check and see if the application branch is there in this list ?

**Comment by karthikvijay** [comment]
If I pull the branch again, will it affect the changes which i have made

**Comment by AbdealiJK** [comment]
Not sure ... depends on what all you've done till now :P

So, first why dont u try to run `git branch -a` and check if the problem is what i mentioned ... (it may turn out that you dont need to pull)

**Comment by karthikvijay** [comment]
git pull doesn't work in pulling in the remote branch. i found this link:
 http://stackoverflow.com/questions/9537392/git-fetch-remote-branch
and it tells to run the comand
```
git fetch <remote> <rbranch>:<lbranch> 
``` 
and that worked
