### ISSUE TITLE
file uploads

### ISSUE THREAD

**Issue by karthikvijay** [AbdealiJK/dashboard#20]

**Comment by karthikvijay** [comment]
I could upload the files and store the path of the filename in the corresponding application/core models.
but in this link: http://joelennon.com/file-uploads-with-express-4-0/ 
there is a warning given

WARNING When you have finished processing the uploaded file you should delete it from the filesystem. Otherwise an attacker could easily write a script that will bombard your server with file uploads in an attempt to fill its hard disk and bring the server down. If you need to store the file, consider storing it in a purpose-built file store such as Amazon S3, or adding security measures around the upload page.

I couldn't understand what that means

**Comment by AbdealiJK** [comment]
Forget about the warning.
Have you been able to save the filepath into the express ?
Now, display the models and in that give a link to download that file

**Comment by karthikvijay** [comment]
Yes I can save the filepath into the expressjs
Now , do i have to create a another page displaying all the models and give a link over there for downloading??

**Comment by AbdealiJK** [comment]
Yes, that would be the "list" page right ?
