### ISSUE TITLE
problem in file uploading

### ISSUE THREAD

**Issue by karthikvijay** [AbdealiJK/dashboard#23]
actually I can upload files in creating models. Actually I am writing the same code while updating also but files are not getting  uploaded. I cant figure out the error here.
controller for the update is 
```
exports.update= function(req, res, next){
    console.log('hihi'+req.params.uid); 
    app.use(multer({dest:'./uploadsa/'}));  
}  
```
i have not included the logic for uploading coz update is not working.

ejs file for edit.ejs which includes the action for update
```
<form action="/application/update/<%= application.id %>" method="POST" class="form-signin">
<h2> Edit Your Details </h2>
<input value="<%= application.name %>" name="name" type="text"   class="form-control"/><br>
<input value="<%= application.email %>" name="email" type="text"   class="form-control"/><br>
<input value="<%= application.rollno %>" name="rollno" type="text"   class="form-control"/><br>
<input value="<%= application.department %>" name="department" type="text"   class="form-control"/><br>

 <input type="file" name="thumbnail" placeholder="upload your file">

<button type="submit" class="btn btn-primary btn-block" name="submit">Update</button>

</form>
```
corresponding route is 
```
router.route('/update/:uid')
  .post(applicationControllers.update);
```

**Comment by karthikvijay** [comment]
the console.log over there is working

**Comment by AbdealiJK** [comment]
App.use cannot be in Controller... App is not defined there c

**Comment by karthikvijay** [comment]
I have defined the app in the controller.
```
var express        = require('express');
var app= express();

```
it is working in exports.create
```
exports.create = function (req, res) {
  //console.log(req.body);
  app.use(multer({dest:'./uploads/'}));
 // console.log(req.files.thumbnail.path);
  var application = new applicationModel(req.body);
  application.filepath=req.files.thumbnail.path; 
  application.save(function(err) {
   // console.log(req.body);
    
     if ( ! err ) {
      //req.session.flash = messageHelper.createAlert('success', 'Your account has been created !');
      console.dir(application);
     return res.redirect(config.baseUrl);
      } else {
      //req.session.flash = messageHelper.mongoErrorsToAlert(err);
      //console.log('hi');
      console.log(err);
      return res.redirect(config.baseUrl);
    }
  });
};
```
but i dont know what is the problem in exports .update
```
exports.update= function(req, res, next){
    console.log('hihi'+req.params.uid); 
    app.use(multer({dest:'./uploadsa/'})); 
}
```

**Comment by karthikvijay** [comment]
it is working now. i forgot to add 
```
enctype="multipart/form-data" 
```
in the corresponding ejs fiile.

**Comment by AbdealiJK** [comment]
The way you've done it seems to be completely wrong, (no idea why is
working in create )
But that's not the way you use app...
You can only have  ONE app... You can't arbitly define another app on your
controller. App is basically a server, so you created two different servers

I think you should read some tutorial properly on this

**Comment by AbdealiJK** [comment]
I'm pretty sure it's still not the correct way of doing this, can you check
out a tutorial properly?

The multer line was already there in app.js

**Comment by karthikvijay** [comment]
Sorry for making comment in the wrong issue
I understand abt the app thing . But I dont know how to use the multer in my controller otherwise since it is a miidleware. So i defined the app there also to do that.I dont know how to invoke the multer thing in my controller which is defined in app.js 
the other problems are solved.

**Comment by karthikvijay** [comment]
now i have included the 
```
 app.use(multer({dest:'./uploads/'}));
```
in the app.js and removed those lines from my controller .js
 everything is working fine

**Comment by AbdealiJK** [comment]
Yep, that makes more sense ^_^

So, just mentioning, normally you may want to move the file to a specific
folder and change the name to something nice ... like ;
"uploads/applications/<userid>.pdf"

So, try doing that --- This code should be in the controller
