### ISSUE TITLE
Make a simple form

### ISSUE THREAD

**Issue by AbdealiJK** [AbdealiJK/dashboard#3]
For : @shruti1995 @ch14b027 @anirudhravichandran @karthikvijay

**Comment by AbdealiJK** [comment]
Updates ?

Been more than 5 days

**Comment by sai-akshaya** [comment]
Have to go through "dashboard" now.

**Comment by AbdealiJK** [comment]
Has everyone setup dasboard :/

It's disappointing that some people have still not set it up - and we had
discussed that this needed to be done a week ago
